name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install gcc flex bison libglew-dev libsdl2-dev

      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          options: homeworld tools assets
          meson-version: 0.60.0

  build-macos-gcc:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        run: |
          brew install gcc flex bison glew sdl2
          pip install meson ninja

      - name: Build
        run: |
          meson build
          ninja -C build homeworld tools assets
        env:
          CC: gcc

  build-macos-clang:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        run: |
          brew install clang flex bison glew sdl2
          pip install meson ninja

      - name: Build
        run: |
          meson build
          ninja -C build homeworld tools assets
        env:
          CC: clang
